services:
  - type: web
    name: civiclens-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://civiclens-backend-hs7b.onrender.com/api